name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install libcmocka-dev gcovr lcov
    - name: Install gh-pages
      run: sudo npm install -g gh-pages@3.0.0 --save-devi --prefix /usr/

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DTESTS=ON -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target check

    - name: Create Coverage Data
      working-directory: ${{github.workspace}}/build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target coverage

    - name: Evaluate Coverage
      uses: terencetcf/github-actions-lcov-minimum-coverage-checker@v1
      with:
        coverage-file: build/coverage/coverage.info
        minimum-coverage: 90

    - name: Report Coverage
      uses: manarbenkraouda/lcov-reporter-action@v0.3.5.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ${{github.workspace}}/build/coverage/coverage.info

    - name: Deploy
      working-directory: ${{github.workspace}}/build
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        sudo gh-pages -d coverage -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
